name: Delivery

on:
  push:
    branches: [main]

permissions:
  contents: write    

jobs:
  update-tag:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get latest tag information
      id: get_tag_info
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pre_release_branches: main
        default_prerelease_bump: false      
        default_bump: false
        append_to_pre_release_tag: pre        
        tag_prefix: v

    - name: Determine required bump type
      id: determine_bump
      run: |
        PREVIOUS_TAG="${{ steps.get_tag_info.outputs.previous_tag }}"
        BUMP_TYPE="prepatch"

        if [[ -n "$PREVIOUS_TAG" && "$PREVIOUS_TAG" == *"-pre"* ]]; then
          BUMP_TYPE="prerelease"
          echo "Previous tag '$PREVIOUS_TAG' is a pre-release. Setting bump type to: $BUMP_TYPE"
        elif [[ -n "$PREVIOUS_TAG" ]]; then
          echo "Previous tag '$PREVIOUS_TAG' is stable. Setting bump type to default: $BUMP_TYPE"
        else
          echo "No previous tag found. Setting bump type to default: $BUMP_TYPE"
        fi

        echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT

    - name: Create new pre-release tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pre_release_branches: main
        default_prerelease_bump: ${{ steps.determine_bump.outputs.bump_type }}
        append_to_pre_release_tag: pre
        tag_prefix: v