name: Integration CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'docs/**'
      - '*.md'

jobs:
  ci-pipeline-smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache DVC data cache
        uses: actions/cache@v4
        with:
          path: .dvc/cache
          key: dvc-cache-${{ runner.os }}-${{ hashFiles('dvc.lock') }}
          restore-keys: |
            dvc-cache-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pylint
        run: pylint src/

      - name: Run flake8
        run: flake8 src/

      - name: Run bandit
        run: bandit -r src/

      - name: DVC pull
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Pulling DVC data..."
          dvc pull
          echo "DVC pull completed."
      
      - name: Run DVC pipeline
        run: |
          echo "Running DVC pipeline..."
          dvc repro
          echo "DVC pipeline completed."

      - name: Check for uncommitted changes in dvc.lock or .dvc files
        run: |
          git config --global user.name "ci"
          git config --global user.email "ci@example.com"

          git add dvc.lock *.dvc
          if ! git diff --cached --quiet; then
            echo "::error::dvc.lock or .dvc files have changed. Please run 'dvc repro' and commit the updated files." >&2
            git diff --cached  # Optional: show what changed in logs
            exit 1
          fi
